dist: focal
language: python
python:
  - "3.11"
install:
    - pip install -r requirements.txt
env:
  global:
    - CC_TEST_REPORTER_ID=3c448c2cd404dde6685fa0904971bc68d1ac990a2c268a511a9e139d578d58aa
    - PORT=5037
    - LOCAL_URL=http://192.168.80.200:62000
    - TERRAI_INDEX_ID=index_1dca5597d6ac406482cf9f02b178f424
    - TERRAI_DATASET_ID=1dca5597-d6ac-4064-82cf-9f02b178f424
    - GATEWAY_URL=http://127.0.0.1:9000
    - AWS_REGION=us-east-1
    - MICROSERVICE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --source=gladanalysis -m unittest -v gladanalysis.tests
after_script:
  - coverage report
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
