develop:
  extends:
    file: base.yml
    service: base
  container_name: forest-change-analysis-elastic-test
  environment:
    LOCAL_URL: http://192.168.80.200:62000
    DEBUG: "True"
  command: test
