develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "62000:62000"
  container_name: forest-change-analysis-elastic-develop
  environment:
    CT_REGISTER_MODE: auto
    ENVIRONMENT: staging
    API_VERSION: v1
    DEBUG: "True"
    CT_URL: http://192.168.80.164:9000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
    LOCAL_URL: http://192.168.80.164:62000
    TERRAI_INDEX_ID: index_80a4852d8b2d4641977adacb845acb70
    TERRAI_DATASET_ID: 80a4852d-8b2d-4641-977a-dacb845acb70
    GLAD_INDEX_ID: index_d6268f65e4cf4a1a9435fb52a1c7ddd0
    GLAD_DATASET_ID: d6268f65-e4cf-4a1a-9435-fb52a1c7ddd0
  command: develop
  volumes:
    - ./gladanalysis:/opt/forest-change-analysis-elastic/gladanalysis
  restart: always
