develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "62000:62000"
  container_name: glad-sql-analysis
  environment:
    ENVIRONMENT: staging
    API_VERSION: v1
    DEBUG: "True"
    CT_URL: http://192.168.80.200:9000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
    LOCAL_URL: http://192.168.80.200:62000
    TERRAI_INDEX_ID: index_bb80312eb51448ad9252336408603591
    TERRAI_DATASET_ID: bb80312e-b514-48ad-9252-336408603591
    GLAD_INDEX_ID: index_e663eb0904de4f39b87135c6c2ed10b5
    GLAD_DATASET_ID: e663eb09-04de-4f39-b871-35c6c2ed10b5
  command: develop
  volumes:
    - ./gladanalysis:/opt/glad-sql-analysis/gladanalysis
  restart: always
