prod:
  image: vizzuality/forest-change-analysis-elastic:0.0.1${STAGING}
  ports:
    - "62000"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: forest-change-analysis-elastic${STAGING}
