version: "3"
services:
  develop:
    build: .
    ports:
      - "62000:62000"
    container_name: forest-change-analysis-elastic-develop
    environment:
      ENVIRONMENT: staging
      PORT: 62000
      DEBUG: "True"
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      LOCAL_URL: http://mymachine:62000
      TERRAI_INDEX_ID: index_bb80312eb51448ad9252336408603591_1536262007962
      TERRAI_DATASET_ID: bb80312e-b514-48ad-9252-336408603591
    command: develop
    volumes:
      - ./gladanalysis:/opt/forest-change-analysis-elastic/gladanalysis
    restart: always
