apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "62000"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://{name}.default.svc.cluster.local:62000
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: TERRAI_INDEX_ID
            value: index_47c17b4fa7624990ba1fc4759aaddd91
          - name: TERRAI_DATASET_ID
            value: 47c17b4f-a762-4990-ba1f-c4759aaddd91
          - name: GLAD_INDEX_ID
            value: index_1c1320f1dd9e42b2b840950a6f43084e
          - name: GLAD_DATASET_ID
            value: 1c1320f1-dd9e-42b2-b840-950a6f43084e

        ports:
          - containerPort: 62000

      restartPolicy: Always
