apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: forest-change
  name: forest-change
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: forest-change
    spec:
      containers:
      - name: forest-change
        image: vizzuality/forest-change
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "62000"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://forest-change.gfw.svc.cluster.local:62000
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: TERRAI_INDEX_ID
            value: index_bb80312eb51448ad9252336408603591_1536262007962
          - name: TERRAI_DATASET_ID
            value: bb80312e-b514-48ad-9252-336408603591

        ports:
          - containerPort: 62000

      restartPolicy: Always
